language: cpp
branches:
  only:
  - master
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt install libgtest-dev -y
script:
- mkdir gtest
- cd gtest
- cmake /usr/src/gtest/
- cmake --build .
- sudo cp *.a /usr/lib/
- cd ..
- sudo apt-get install python3-venv
- python3 -m venv venv
- . venv/bin/activate
- pip install conan
- mkdir build
- cd build
- conan install  -s compiler.libcxx=libstdc++11 ..
- cmake ..
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -v -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uvaefremov:$BINTRAY_API_KEY "https://api.bintray.com/content/vaefremov/otus_hw/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
